### ISSUE TITLE
Missing try/except for Bio.Alphabet in abutils/core/pair.py

### ISSUE THREAD

**Issue by zacmon** [briney/abstar#89]
There should be
```python
try:
    from Bio.Alphabet import generic_dna
except ImportError:
        generic_dna = 'DNA'
```

in `abutils/core/pair.py` similar to the other commits you made recently otherwise abstar 0.4.3 does not work for me immediately after pip installing.

Or perhaps the problem is that upgrading my abstar from 0.3.5 to 0.4.3 didn't also upgrade to the latest abutils . . .

**Comment by briney** [comment]
Yeah, it looks like an old version of abutils is to blame. I'll update requirements..txt to specify the appropriate abutils version.
